baseURL = "https://www.aquriousmind.com"
languageCode = "en-us"
title = "A Qurious Mind"
theme = "ananke"
googleAnalytics = "UA-186172134-1"

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]

  [[menu.main]]
    name = "Stories"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/categories/stories/"
    weight = -30

  [[menu.main]]
    identifier = "Activities"
    name = "Activities"
    pre = "<i class='fa fa-heart'></i>"
    url = "/categories/activities/"
    weight = -10

  [[menu.main]]
    name = "Blog"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/categories/blog/"
    weight = -5

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/corner/"
    weight = -1

[params]
  custom_css = ["css/custom.css"]
  